@startuml
class Prenda {
~ TipoPrenda tipo
~ String material
~ String colorPrimario
~ String colorSecundario
+ Categoria getCategoria()
+ String getColorSecundario()
+ setColorSecundario(String)
}
class TipoPrenda {
~ Categoria categoria
+ Categoria getCategoria()
}
Enum Categoria {
}

Prenda -> TipoPrenda
TipoPrenda -> Categoria
@enduml