@startuml
class Prenda {
~ TipoPrenda tipo
~ Material material
~ Color colorPrimario
~ Color colorSecundario
+ Categoria getCategoria()
+ String getColorSecundario()
+ setColorSecundario(String)
}
class Color{
~ Integer red
~ Integer green
~ Integer blue
}
Enum TipoPrenda {
~ Categoria categoria
+ Categoria getCategoria()
}
Enum Categoria {
}

Enum Material{
}

Prenda -> Material
Prenda -> TipoPrenda
TipoPrenda -> Categoria
Prenda -> Color
@enduml